odevpl/wdp-2301

- src/components/common/ProductBox/ProductBox.module.scss
add change styles buttons in ProductBox
> pull request from task WDP230101-4

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/redux/initialState.js
1. I added new field to initialState : isFavourite and isComparable (with boolean value)
2. I added additional param to ProductBox
3. I added new style class based on isComparable and isFavourite
> WDP230101-5 Add isFavouirite and isComparable params into ProductBox component

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/redux/initialState.js
Add display of old price in component ProductBox.
> bug-WDP230101 6

- src/components/features/ProductSearch/ProductSearch.js
- src/components/features/ProductSearch/ProductSearch.module.scss
1. remove select element 
2. get Categories from initialState
3. use ul / li elements to display 
4. add new styles for this elements
> WDP230101-10 Add hover list on search category area

- src/styles/settings.scss
> pull request from task WDP230101-8

- src/components/common/ProductBox/ProductBox.module.scss
- src/components/features/ProductSearch/ProductSearch.module.scss
I fixed non resolved conflict that failed the app
> fix unresolved conflict

- src/components/layout/Footer/Footer.js
> pull request from task WDP230101-18

- src/components/common/ProductBox/ProductBox.module.scss
- src/components/features/NewFurniture/NewFurniture.js
- src/components/features/NewFurniture/NewFurniture.module.scss
> task-WDP230101-17

- package.json
- src/components/common/ProductBox/ProductBox.js
- src/components/common/Swipeable/Swipeable.js
- src/components/common/Swipeable/Swipeable.module.scss
- src/components/common/Swipeable/Swipeable.test.js
- src/components/features/NewFurniture/NewFurniture.js
- src/components/features/ProductSearch/ProductSearch.js
- src/redux/initialState.js
- yarn.lock
1. Add new component Swipeable with tests:
- Add swipeable functionality on Buttons, swiping and touching on mobile devices.
3. Create new state pageCounter
4. Add new functions for Swipeable
5. Implement Swipeable at NewFurniture
6. Resolved the conflicts
> WDP230101-13 Add common Swipeable wrapper component, used on NewFurniture.js

- src/components/features/ProductSearch/ProductSearch.js
- src/components/features/ProductSearch/ProductSearch.test.js
- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- src/components/layout/TopBar/TopBar.module.scss
> Wdp230101 15

- src/components/common/ProductBox/ProductBox.js
- src/components/features/ProductSearch/ProductSearch.js
- src/components/features/ProductSearch/ProductSearch.module.scss
- src/components/features/ProductSearch/ProductSearch.test.js
- src/components/layout/MenuBar/MenuBar.js
- src/components/layout/MenuBar/MenuBar.module.scss
- yarn.lock
> pull request from task WDP-14

- src/components/common/ProductBox/ProductBox.js
- src/components/common/Stars/Stars.js
- src/components/common/Stars/Stars.module.scss
- src/redux/initialState.js
- src/redux/productsRedux.js
> pull request from task WDP230101-21

- src/components/common/ProductBox/ProductBox.js
- src/components/common/Swipeable/Swipeable.module.scss
- src/components/features/Popup/Popup.js
- src/components/features/Popup/Popup.module.scss
- src/components/features/Popup/Popup.test.js
1. Add Popup component
2. Use Popup component in ProductBox
3. Show product information, on QuickView button.
> Add Popup component

- src/App.js
- src/components/features/Popup/Popup.js
- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/layout/TopBar/TopBar.js
- src/components/views/Register/Register.js
- src/components/views/Register/Register.module.scss
- src/components/views/Register/Register.test.js
1. Add Register component
2. Add route path for Register component
3. Fix PropType argument in Popup component
> wdp-47 Add Register Component

- src/App.js
- src/components/layout/TopBar/TopBar.js
- src/components/views/Login/Login.js
- src/components/views/Login/Login.module.scss
- src/styles/settings.scss
> pull request from task WDP-53

- src/App.js
- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/views/Cart/Cart.js
- src/components/views/Cart/Cart.module.scss
- src/components/views/Cart/Cart.test.js
1. Add Cart component without RWD and functionality (only static view)
2. Add styles for Cart, similar to whole page
> wdp-49 Add Cart component

- package-lock.json
- src/components/views/Register/Register.js
- src/components/views/Register/Register.module.scss
- yarn.lock
1. Add showing and hiding password on 'Pokaż hasło'.
2. Add validation for inputs.
3. If all inputs are correct move user to home.
> wdp-48 Add functionality in Register component.

- package-lock.json
- package.json
- src/components/views/Login/Login.js
- src/components/views/Login/Login.module.scss
- src/redux/productsRedux.js
- yarn.lock
> pull request from task WDP-54

- src/components/common/ProductBox/ProductBox.js
- src/components/views/Cart/Cart.js
- src/components/views/Cart/Cart.module.scss
- src/redux/cartRedux.js
- src/redux/initialState.js
- src/redux/productsRedux.js
1. Add possibility to increse quantity of product in cart. 
2. Add counting for total price.
3. prevent the same product from being added to the cart twice.
> WDP-59 Add price handlers in Cart Component

- src/components/views/Cart/Cart.js
- src/components/views/Cart/Cart.module.scss
> small-fix-for-cartView
